Feature/lesson2
micolla/WebStoreASP pull request #4
Opened 2019-11-15 14:31 UTC by micolla

2019-11-16 09:38 UTC, Infarh requested changes
Нужно поменять тип модели в представлении `GetEmployees.cshtml` с `@model IEnumerable<WebStoreASP.ViewModels.EmployeeView>` на `@model IEnumerable<WebStore.ViewModels.EmployeeView>`

2019-11-18 06:17 UTC, merged

2019-11-18 11:07 UTC, Infarh commented on WebStoreASP/Views/Shared/Partial/_Scripts.cshtml
> +<script src="js/main.js"></script>
Не хватает ~ в начале адреса

2019-11-18 11:08 UTC, Infarh commented on Tests/WebStoreTests/ViewModels/EmployeeViewTest.cs
> +                                        FirstName = "�������",
Беда с кодировкой...

2019-11-18 11:32 UTC, micolla commented on Tests/WebStoreTests/ViewModels/EmployeeViewTest.cs
> +                                        FirstName = "�������",
странно вижу везде нормально и в гите, и в студии. Кодировка UTF-8 BOM